name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build on ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            GOOS: linux
            GOARCH: amd64
            output: cache-kv-purger-linux-amd64
          - os: macos-latest
            GOOS: darwin
            GOARCH: amd64
            output: cache-kv-purger-darwin-amd64
          - os: windows-latest
            GOOS: windows
            GOARCH: amd64
            output: cache-kv-purger-windows-amd64.exe
    
    runs-on: ${{ matrix.os }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
        cache: true

    - name: Build
      run: go build -v -o ${{ matrix.output }} ./cmd/cli
      env:
        GOOS: ${{ matrix.GOOS }}
        GOARCH: ${{ matrix.GOARCH }}

    - name: Upload binary as artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.output }}
        path: ./${{ matrix.output }}
        retention-days: 7

  test:
    name: Test on Ubuntu
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
        cache: true

    - name: Run tests
      run: go test -v ./...

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        # Fetch all history for better linting context
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
        cache: true

    # If you want to allow linting to auto-fix some issues
    - name: Install golangci-lint
      run: |
        curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.55.2
        $(go env GOPATH)/bin/golangci-lint --version

    # Run lint without failing the build on lint errors
    # This allows builds to complete even with style issues
    - name: Run golangci-lint (advisory)
      run: $(go env GOPATH)/bin/golangci-lint run ./...
      continue-on-error: true
